### ISSUE TITLE
Level Select Screen

### ISSUE THREAD

**Issue by watce001** [watce001/Anti-V1rus#1]
Make a level select screen that looks similar to the one I made in the design document. Doesn't need to be flashy, just functional

**Comment by cozrator** [comment]
Level select screen us been implemented. The start button on the menu screen has been redirected to point to the level select and the code for going into level one has been moved to a button on the level select screen. There are also buttons for levels 2 and 3 that show a coming soon dialog box when pressed. The coming soon dialog box is off center at the moment though and will need to be fixed when we start working on our custom UI.
